### ISSUE TITLE
tab-search-smarter issue with addons.json

### ISSUE THREAD

**Issue by grahamperrin** [maximstewart/Tab-Search-Firefox#2]
From my Waterfox `addons.json`, for the extension (currently named _Tab Search and Manage_) that I might have first installed a few months ago: 

`{"id":"tabsSearch@itdominator.com","icons":{"32":"https://addons.cdn.mozilla.net/user-media/addon_icons/902/902061-32.png?modified=1525569623","64":"https://addons.cdn.mozilla.net/user-media/addon_icons/902/902061-64.png?modified=1525569623"},"type":"extension","name":"Tab Search","version":"1.1.8","creator":{"name":"ITDominator","url":"https://addons.mozilla.org/en-GB/firefox/user/ITDominator/?src=api"},"description":"Search tabs and switch to them quickly! This plugin will will generate a list if there is more than one tab present for the query. Otherwise, it will select the tab that matches the search term given.","fullDescription":null,"developerComments":null,"eula":null,"screenshots":[{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/201/201343.png?src=api&modified=1525220405","width":"700","height":"524","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/201/201343.png?src=api&modified=1525220405","thumbnailWidth":"200","thumbnailHeight":"150","caption":"Shows all tabs before search."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/201/201344.png?src=api&modified=1525220405","width":"674","height":"525","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/201/201344.png?src=api&modified=1525220405","thumbnailWidth":"192","thumbnailHeight":"150","caption":"Tabs after search."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/201/201345.png?src=api&modified=1525220405","width":"700","height":"522","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/201/201345.png?src=api&modified=1525220405","thumbnailWidth":"200","thumbnailHeight":"149","caption":"Drag and drop tab management."}],"homepageURL":"https://www.itdominator.com/","learnmoreURL":"https://addons.mozilla.org/en-GB/firefox/addon/tab-search-smarter/?src=api","supportURL":"https://github.com/maximstewart/Tab-Search-Firefox","averageRating":0,"reviewCount":0,"reviewURL":"https://addons.mozilla.org/en-GB/firefox/addon/tab-search-smarter/reviews/?src=api","totalDownloads":191,"weeklyDownloads":8,"dailyUsers":38,"repositoryStatus":4,"updateDate":1525568428000,"isPlatformCompatible":false}`

The `learnmoreURL` and `reviewURL` values are wrong, probably outdated; https://addons.mozilla.org/addon/tab-search-smarter/ is not found. 

I guess, the AMO `tab-search-smarter` slug was changed to `tab-search-and-manage` – @maximstewart, is that so?

Also: 

- the version above (1.1.8) does not match the installed version (1.2.9)
- there _was_ a version 1.1.8 at https://addons.mozilla.org/addon/tab-search-and-manage/versions/?page=1#version-1.1.8 that's listed as _Tab Search and Manage_ but I wonder whether the name was different at the time of 1.1.8
- `1.2.9` is nowhere in `addons.json`.

As far as I can tell, I can not reproduce the wrongness with addition of the extension from https://addons.mozilla.org/addon/tab-search-and-manage/ to a new profile.

**Comment by maximstewart** [comment]
"I guess, the AMO tab-search-smarter slug was changed to tab-search-and-manage – @maximstewart, is that so?"

This is correct as I wanted to make it clearer what the plugin could and couldn't do so did a name change.

"the version above (1.1.8) does not match the installed version (1.2.9)"

I at one point did an overhaul of the themeing and the name change was a part of that. I have another plugin that I'm working on that this plugin branched from. The other plugin is in limbo as the idea for it was/is for it to mimic Firefox's Tabgroups functionality.

https://addons.mozilla.org/en-US/firefox/addon/tab-groups-with-search-manager/

"As far as I can tell, I can not reproduce the wrongness with addition of the extension from"

I'm not sure what's wrong that you are referencing?

**Comment by grahamperrin** [comment]
Thanks, I saw the other extension. 

> I'm not sure what's wrong that you are referencing?

The wrongness is within the `addons.json` in the affected Waterfox profile. 

Maybe best described as _staleness_. It surprises me that I can remove the extension, quit Waterfox, start Waterfox, add the extension then (behind the scenes) **not** find proper information in `addons.json`. 

Without looking behind the scenes, the problem was first observed when I used [Add-ons Manager Context Menu](https://addons.mozilla.org/addon/am-context/) to open the AMO page for the installed extension. Still observable (screen recording to follow) …

- 

I guess, I _might_ work around by again removing the extension, quitting Waterfox and then manually editing out the wrong part of the file. Do-able, but extraordinary.

**Comment by maximstewart** [comment]
"Waterfox, add the extension then (behind the scenes) not find proper information in addons.json."

XD I'm deff gunna need to see a vid of this as I'm still not clear on what's stale.

You had said before this:   "The learnmoreURL and reviewURL values are wrong, probably outdated..."
Is this the staleness you speak of?

**Comment by grahamperrin** [comment]
Thanks … I need to make a new screen recording. 

(The recording that I made yesterday was confused by the Remove button not working in one context at `about:addons`.)

**Comment by grahamperrin** [comment]
Recording: https://photos.app.goo.gl/iZ1Tm1sJzNyKZAs46

**Comment by maximstewart** [comment]
Hey, OK, I got a chance to look at your video and see what you mean. I'm not sure why it's not showing incorrectly your end as I looked at my addons.js file and it shows the proper name and version number.

Here's my video.
[Uploading 2018-10-05 00-14-52.mkv.zip…]()

**Comment by grahamperrin** [comment]
> Uploading 2018-10-05 00-14-52.mkv.zip…

I can't view the video :-) but I'm sure that it's fine for you. 

I _imagine_ that the issue might be reproducible if begun with an installation of outdated 1.1.8 but it's probably not worth troubleshooting. 

Instead, I'll try a manual edition of `addons.js`

**Comment by maximstewart** [comment]
The video is zipped and is n mkv. Ummm, OK, if you want to do the edit then good luck! I'll close this bug then.

**Comment by grahamperrin** [comment]
Thanks, incidentally it appears that your previous comment was submitted before upload of the `.zip` completed …

**Comment by grahamperrin** [comment]
OK, I quit Waterfox, removed the troublesome part from `addons.json` then started Waterfox and added outdated version 1.2.**8**. 

### Result

At the tail of the file, this, with 1.2.**9** (not 1.2.8): 

`{"id":"tabsSearch@itdominator.com","icons":{"32":"https://addons.cdn.mozilla.net/user-media/addon_icons/902/902061-32.png?modified=1527200423","64":"https://addons.cdn.mozilla.net/user-media/addon_icons/902/902061-64.png?modified=1527200423"},"name":"Tab Search and Manage","type":"extension","version":"1.2.9","repositoryStatus":4,"creator":{"name":"ITDominator","url":"https://addons.mozilla.org/en-GB/firefox/user/ITDominator/?src=api"},"description":"This plugin can search, drag-n-drop ordering, and (un)hide all or some tabs. A search redirects automatically if the search is found and is a single instance. Search multiple windows by toggling the window icon on the bottom.","fullDescription":null,"isPlatformCompatible":true,"eula":null,"screenshots":[{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202748.png?src=api&modified=1530209521","width":"762","height":"576","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202748.png?src=api&modified=1530209521","thumbnailWidth":"265","thumbnailHeight":"200","caption":"Default list style without interacting with tab."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202749.png?src=api&modified=1530209522","width":"760","height":"572","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202749.png?src=api&modified=1530209522","thumbnailWidth":"266","thumbnailHeight":"200","caption":"Hovering on tab."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202750.png?src=api&modified=1530209524","width":"761","height":"572","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202750.png?src=api&modified=1530209524","thumbnailWidth":"266","thumbnailHeight":"200","caption":"List of tabs matching search."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202751.png?src=api&modified=1530209526","width":"1280","height":"454","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202751.png?src=api&modified=1530209526","thumbnailWidth":"320","thumbnailHeight":"114","caption":"3 tabs hidden and three shown."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202752.png?src=api&modified=1530209528","width":"1280","height":"456","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202752.png?src=api&modified=1530209528","thumbnailWidth":"320","thumbnailHeight":"114","caption":"All tabs but current active hidden."},{"url":"https://addons.cdn.mozilla.net/user-media/previews/full/202/202753.png?src=api&modified=1530209529","width":"759","height":"255","thumbnailURL":"https://addons.cdn.mozilla.net/user-media/previews/thumbs/202/202753.png?src=api&modified=1530209529","thumbnailWidth":"320","thumbnailHeight":"108","caption":"Search failed response."}],"averageRating":4,"learnmoreURL":"https://addons.mozilla.org/en-GB/firefox/addon/tab-search-and-manage/?src=api","homepageURL":"https://www.itdominator.com/","sourceURI":"https://addons.mozilla.org/firefox/downloads/file/1093800/tab_search_and_manage-1.2.9-fx.xpi?src=api","size":64617,"developerComments":null,"reviewURL":"https://addons.mozilla.org/en-GB/firefox/addon/tab-search-and-manage/reviews/?src=api","reviewCount":2,"totalDownloads":358,"weeklyDownloads":22,"dailyUsers":35,"updateDate":1538345407000,"supportURL":"https://github.com/maximstewart/Tab-Search-Firefox"}]}`

– properly represented as 1.2.8 at about:addons

![2018-10-08 06 33 59 add-ons manager](https://user-images.githubusercontent.com/192271/46593494-5bf53f00-cac4-11e8-990a-93e2ab52a676.png)

– and a manual check for updates finds the update from 1.2.8 to 1.2.9: 

![2018-10-08 06 34 23 add-ons manager](https://user-images.githubusercontent.com/192271/46593509-77604a00-cac4-11e8-8c59-fda5a2359871.png)

**Comment by grahamperrin** [comment]
I stumbled across comparable symptoms affecting a different extension, in Firefox, so I raised this: 

- Mozilla bug [1497387 - Outdated, stale extensions metadata in addons.json](https://bugzilla.mozilla.org/show_bug.cgi?id=1497387)

**Comment by maximstewart** [comment]
Ahhh, OK, sounds good!!
